/// <reference path="//Microsoft.WinJS.0.6/js/base.js" /> 
/// <reference path="//Microsoft.WinJS.0.6/js/ui.js" /> 
(function () {
    "use strict";

    //Низа од сите можни слики во албумот
    //За семинарска до нив ќе се пристапува преку Web сервис
    var sliki = [
        { tim: 'Lakers', ime: 'Kobe Bryant', pozicija: 'Guard', broj: '24', slika: '/images/Lakers/kobe_bryant.jpg' },
      	{ tim: 'Lakers', ime: 'Steve Blake', pozicija: 'Guard', broj: '5', slika: '/images/Lakers/steve_blake.jpg' },
      	{ tim: 'Lakers', ime: 'Earl Clark', pozicija: 'Forward', broj: '6', slika: '/images/Lakers/earl_clark.jpg' },
      	{ tim: 'Lakers', ime: 'Chris Duhon', pozicija: 'Forward', broj: '21', slika: '/images/Lakers/chris_duhon.jpg' },
      	{ tim: 'Lakers', ime: 'Devin Ebanks', pozicija: 'Guard', broj: '24', slika: '/images/Lakers/devin_ebanks.jpg' },
      	{ tim: 'Lakers', ime: 'Pau Gasol', pozicija: 'Center', broj: '16', slika: '/images/Lakers/pau_gasol.jpg' },
      	{ tim: 'Lakers', ime: 'Jordan Hill', pozicija: 'Center', broj: '27', slika: '/images/Lakers/jordan_hill.jpg' },
      	{ tim: 'Lakers', ime: 'Dwight Howard', pozicija: 'Center', broj: '12', slika: '/images/Lakers/dwight_howard.jpg' },
      	{ tim: 'Lakers', ime: 'Antawn Jamison', pozicija: 'Forward', broj: '4', slika: '/images/Lakers/antawn_jamison.jpg' },
      	{ tim: 'Lakers', ime: 'Darius Johnson-Odom', pozicija: 'Guard', broj: '7', slika: '/images/Lakers/darius_johnson-odom.jpg' },
      	{ tim: 'Lakers', ime: 'Jodie Meeks', pozicija: 'Guard', broj: '20', slika: '/images/Lakers/jodie_meeks.jpg' },
      	{ tim: 'Lakers', ime: 'Darius Morris', pozicija: 'Guard', broj: '1', slika: '/images/Lakers/darius_morris.jpg' },
      	{ tim: 'Lakers', ime: 'Steve Nash', pozicija: 'Guard', broj: '10', slika: '/images/Lakers/steve_nash.jpg' },
      	{ tim: 'Lakers', ime: 'Robert Sacre', pozicija: 'Center', broj: '50', slika: '/images/Lakers/robert_sacre.jpg' },
      	{ tim: 'Lakers', ime: 'Metta World Peace', pozicija: 'Forward', broj: '15', slika: '/images/Lakers/metta_world_peace.jpg' },
        { tim: 'Clippers', ime: 'Matt Barns', pozicija: 'Forward', broj: '22', slika: '/images/Clippers/matt_barnes.jpg' },
        { tim: 'Clippers', ime: 'Chauncey Billups', pozicija: 'Guard', broj: '1', slika: '/images/Clippers/chauncey_billups.jpg' },
        { tim: 'Clippers', ime: 'Eric Bledsoe', pozicija: 'Guard', broj: '12', slika: '/images/Clippers/eric_bledsoe.jpg' },
        { tim: 'Clippers', ime: 'Caron Butler', pozicija: 'Forward', broj: '5', slika: '/images/Clippers/caron_butler.jpg' },
        { tim: 'Clippers', ime: 'Jamal Crawford', pozicija: 'Guard', broj: '11', slika: '/images/Clippers/jamal_crawford.jpg' },
        { tim: 'Clippers', ime: 'Willie Green', pozicija: 'Guard', broj: '34', slika: '/images/Clippers/willie_green.jpg' },
        { tim: 'Clippers', ime: 'Blake Griffin', pozicija: 'Forward', broj: '32', slika: '/images/Clippers/blake_griffin.jpg' },
        { tim: 'Clippers', ime: 'Grant Hill', pozicija: 'Forward', broj: '33', slika: '/images/Clippers/grant_hill.jpg' },
        { tim: 'Clippers', ime: 'Ryan Hollins', pozicija: 'Forward', broj: '15', slika: '/images/Clippers/ryan_hollins.jpg' },
        { tim: 'Clippers', ime: 'DeAndre Jordan', pozicija: 'Center', broj: '6', slika: '/images/Clippers/deandre_jordan.jpg' },
        { tim: 'Clippers', ime: 'Lamar Odom', pozicija: 'Forward', broj: '7', slika: '/images/Clippers/lamar_odom.jpg' },
        { tim: 'Clippers', ime: 'Chris Paul', pozicija: 'Guard', broj: '3', slika: '/images/Clippers/chris_paul.jpg' },
        { tim: 'Clippers', ime: 'Trey Thompkins', pozicija: 'Forward', broj: '9', slika: '/images/Clippers/trey_thompkins.jpg' },
        { tim: 'Clippers', ime: 'Ronny Turiaf', pozicija: 'Center', broj: '21', slika: '/images/Clippers/ronny_turiaf.jpg' },
        { tim: 'Warriors', ime: 'Harrison Barnes', pozicija: 'Forward', broj: '40', slika: '/images/Warriors/harrison_barnes.jpg' },
       { tim: 'Warriors', ime: 'Andris Biedrins', pozicija: 'Center', broj: '15', slika: '/images/Warriors/andris_biedrins.jpg' },
       { tim: 'Warriors', ime: 'Andrew Bogut', pozicija: 'Center', broj: '12', slika: '/images/Warriors/andrew_bogut.jpg' },
       { tim: 'Warriors', ime: 'Stephen Curry', pozicija: 'Guard', broj: '30', slika: '/images/Warriors/stephen_curry.jpg' },
       { tim: 'Warriors', ime: 'Festus Ezeli', pozicija: 'Center', broj: '31', slika: '/images/Warriors/festus_ezeli.jpg' },
       { tim: 'Warriors', ime: 'Draymond Green', pozicija: 'Forward', broj: '23', slika: '/images/Warriors/draymond_green.jpg' },
       { tim: 'Warriors', ime: 'Jarrett Jack', pozicija: 'Guard', broj: '2', slika: '/images/Warriors/jarrett_jack.jpg' },
       { tim: 'Warriors', ime: 'Richard Jefferson', pozicija: 'Forward', broj: '44', slika: '/images/Warriors/richard_jefferson.jpg' },
       { tim: 'Warriors', ime: 'Charles Jenkins', pozicija: 'Guard', broj: '22', slika: '/images/Warriors/charles_jenkins.jpg' },
       { tim: 'Warriors', ime: 'Carls Landry', pozicija: 'Forward', broj: '7', slika: '/images/Warriors/carl_landry.jpg' },
       { tim: 'Warriors', ime: 'David Lee', pozicija: 'Forward', broj: '10', slika: '/images/Warriors/david_lee.jpg' },
       { tim: 'Warriors', ime: 'Brandon Rush', pozicija: 'Forward', broj: '4', slika: '/images/Warriors/brandon_rush.jpg' },
       { tim: 'Warriors', ime: 'Klay Thompson', pozicija: 'Guard', broj: '11', slika: '/images/Warriors/klay_thompson.jpg' },
       { tim: 'Warriors', ime: 'Jeremy Tyler ', pozicija: 'Forward', broj: '3', slika: '/images/Warriors/jeremy_tyler.jpg' },
       { tim: 'Kings', ime: 'Aaron Brooks', pozicija: 'Guard', broj: '3', slika: '/images/Kings/aaron_brooks.jpg' },
       { tim: 'Kings', ime: 'DeMarcus Cousins', pozicija: 'Center', broj: '15', slika: '/images/Kings/demarcus_cousins.jpg' },
       { tim: 'Kings', ime: 'Tyreke Evans', pozicija: 'Guard', broj: '13', slika: '/images/Kings/tyreke_evans.jpg' },
       { tim: 'Kings', ime: 'Jimmer Fredette', pozicija: 'Guard', broj: '7', slika: '/images/Kings/jimmer_fredette.jpg' },
       { tim: 'Kings', ime: 'Francisco Garcia', pozicija: 'Forward', broj: '32', slika: '/images/Kings/francisco_garcia.jpg' },
       { tim: 'Kings', ime: 'Chuck Hayes', pozicija: 'Forward', broj: '42', slika: '/images/Kings/chuck_hayes.jpg' },
       { tim: 'Kings', ime: 'Tyler Honeycutt', pozicija: 'Forward', broj: '9', slika: '/images/Kings/tyler_honeycutt.jpg' },
       { tim: 'Kings', ime: 'James Johnson', pozicija: 'Forward', broj: '52', slika: '/images/Kings/james_johnson.jpg' },
       { tim: 'Kings', ime: 'Travis Outlaw', pozicija: 'Forward', broj: '25', slika: '/images/Kings/travis_outlaw.jpg' },
       { tim: 'Kings', ime: 'Thomas Robinson', pozicija: 'Forward', broj: '0', slika: '/images/Kings/thomas_robinson.jpg' },
       { tim: 'Kings', ime: 'John Salmons', pozicija: 'Forward', broj: '5', slika: '/images/Kings/john_salmons.jpg' },
       { tim: 'Kings', ime: 'Isaiah Thomas', pozicija: 'Guard', broj: '22', slika: '/images/Kings/isaiah_thomas.jpg' },
       { tim: 'Kings', ime: 'Jason Thompson', pozicija: 'Forward', broj: '34', slika: '/images/Kings/jason_thompson.jpg' },
       { tim: 'Kings', ime: 'Marcus Thornton', pozicija: 'Guard', broj: '23', slika: '/images/Kings/marcus_thornton.jpg' },
       { tim: 'Suns', ime: 'Michael Beasley', pozicija: 'Forward', broj: '0', slika: '/images/Suns/michael_beasley.jpg' },
       { tim: 'Suns', ime: 'Shannon Brown', pozicija: 'Guard', broj: '26', slika: '/images/Suns/shannon_brown.jpg' },
       { tim: 'Suns', ime: 'Goran Dragic', pozicija: 'Guard', broj: '1', slika: '/images/Suns/goran_dragic.jpg' },
       { tim: 'Suns', ime: 'Jared Dudley', pozicija: 'Forward', broj: '3', slika: '/images/Suns/jared_dudley.jpg' },
       { tim: 'Suns', ime: 'Channing Frye', pozicija: 'Center', broj: '8', slika: '/images/Suns/channing_frye.jpg' },
       { tim: 'Suns', ime: 'Marcin Gortat', pozicija: 'Center', broj: '4', slika: '/images/Suns/marcin_gortat.jpg' },
       { tim: 'Suns', ime: 'Wesley Johnson', pozicija: 'Forward', broj: '2', slika: '/images/Suns/wesley_johnson.jpg' },
       { tim: 'Suns', ime: 'Kendall Marshall', pozicija: 'Guard', broj: '12', slika: '/images/Suns/kendall_marshall.jpg' },
       { tim: 'Suns', ime: 'Markieff Morris', pozicija: 'Forward', broj: '11', slika: '/images/Suns/markieff_morris.jpg' },
       { tim: 'Suns', ime: 'Jermaine O’Neal', pozicija: 'Center', broj: '20', slika: '/images/Suns/jermaine_oneal.jpg' },
       { tim: 'Suns', ime: 'Luis Scola', pozicija: 'Forward', broj: '14', slika: '/images/Suns/luis_scola.jpg' },
       { tim: 'Suns', ime: 'Sebastian Telfair', pozicija: 'Guard', broj: '31', slika: '/images/Suns/sebastian_telfair.jpg' },
       { tim: 'Suns', ime: 'P.J Tucker', pozicija: 'Forward', broj: '17', slika: '/images/Suns/pj_tucker.jpg' },
       { tim: 'Suns', ime: 'Luke Zeller', pozicija: 'Forward', broj: '40', slika: '/images/Suns/luke_zeller.jpg' },
       { tim: 'Thunder', ime: 'Kevin Durant', pozicija: 'Forward', broj: '35', slika: '/images/Thunder/kevin_durant.jpg' },
       { tim: 'Thunder', ime: 'Nick Collison', pozicija: 'Forward', broj: '4', slika: '/images/Thunder/nick_collison.jpg' },
       { tim: 'Thunder', ime: 'Serge Ibaka', pozicija: 'Forward', broj: '9', slika: '/images/Thunder/serge_ibaka.jpg' },
       { tim: 'Thunder', ime: 'Perry Jones', pozicija: 'Forward', broj: '3', slika: '/images/Thunder/perry_jones.jpg' },
       { tim: 'Thunder', ime: 'Jeremy Lamb', pozicija: 'Guard', broj: '11', slika: '/images/Thunder/jeremy_lamb.jpg' },
       { tim: 'Thunder', ime: 'Kevin Martin', pozicija: 'Guard', broj: '23', slika: '/images/Thunder/kevin_martin.jpg' },
       { tim: 'Thunder', ime: 'Eric Maynor', pozicija: 'Forward', broj: '6', slika: '/images/Thunder/kevin_martin.jpg' },
       { tim: 'Thunder', ime: 'Daniel Orton', pozicija: 'Center', broj: '33', slika: '/images/Thunder/daniel_orton.jpg' },
       { tim: 'Thunder', ime: 'Kendrick Perkins', pozicija: 'Center', broj: '5', slika: '/images/Thunder/kendrick_perkins.jpg' },
       { tim: 'Thunder', ime: 'Thabo Sefolosha', pozicija: 'Guard', broj: '2', slika: '/images/Thunder/thabo_sefolosha.jpg' },
       { tim: 'Thunder', ime: 'Russell Westbrook', pozicija: 'Guard', broj: '0', slika: '/images/Thunder/russell_westbrook.jpg' },
       { tim: 'Blazers', ime: 'LaMarcus Aldridge', pozicija: 'Forward', broj: '12', slika: '/images/Blazers/lamarcus_aldridge.jpg' },
       { tim: 'Blazers', ime: 'Luke Babbitt', pozicija: 'Forward', broj: '8', slika: '/images/Blazers/luke_babbitt.jpg' },
       { tim: 'Blazers', ime: 'Will Barton', pozicija: 'Guard', broj: '5', slika: '/images/Blazers/will_barton.png' },
       { tim: 'Blazers', ime: 'Nicolas Batum', pozicija: 'Forward', broj: '88', slika: '/images/Blazers/nicolas_batum.jpg' },
       { tim: 'Blazers', ime: 'Victor Claver', pozicija: 'Forward', broj: '18', slika: '/images/Blazers/victor_claver.png' },
       { tim: 'Blazers', ime: 'Joel Freeland', pozicija: 'Center', broj: '19', slika: '/images/Blazers/joel_freeland.png' },
       { tim: 'Blazers', ime: 'J.J. Hickson', pozicija: 'Forward', broj: '21', slika: '/images/Blazers/jj_hickson.jpg' },
       { tim: 'Blazers', ime: 'Jered Jeffries', pozicija: 'Forward', broj: '1', slika: '/images/Blazers/jared_jeffries.jpg' },
       { tim: 'Blazers', ime: 'Mayers Leonard', pozicija: 'Center', broj: '11', slika: '/images/Blazers/meyers_leonard.jpg' },
       { tim: 'Blazers', ime: 'Damian Lillard', pozicija: 'Guard', broj: '0', slika: '/images/Blazers/damian_lillard.jpg' },
       { tim: 'Blazers', ime: 'Wesley Matthews', pozicija: 'Guard', broj: '2', slika: '/images/Blazers/wesley_matthews.jpg' },
       { tim: 'Blazers', ime: 'Sasha Pavlovic', pozicija: 'Guard', broj: '3', slika: '/images/Blazers/sasha_pavlovic.png' },
       { tim: 'Blazers', ime: 'Ronnie Price', pozicija: 'Guard', broj: '24', slika: '/images/Blazers/ronnie_price.jpg' },
       { tim: 'Timberwolves', ime: 'Lou Amudson', pozicija: 'Forward', broj: '17', slika: '/images/Timberwolves/lou_amundson.jpg' },
       { tim: 'Timberwolves', ime: 'Jose Barea', pozicija: 'Gouard', broj: '11', slika: '/images/Timberwolves/jose_barea.jpg' },
       { tim: 'Timberwolves', ime: 'Chase Budinger', pozicija: 'Forward', broj: '10', slika: '/images/Timberwolves/chase_budinger.jpg' },
       { tim: 'Timberwolves', ime: 'Dante Cunningham', pozicija: 'Forward', broj: '33', slika: '/images/Timberwolves/dante_cunningham.jpg' },
       { tim: 'Timberwolves', ime: 'Josh Howard', pozicija: 'Guard', broj: '5', slika: '/images/Timberwolves/josh_howard.jpg' },
       { tim: 'Timberwolves', ime: 'Andrei Kirilenko', pozicija: 'Forward', broj: '47', slika: '/images/Timberwolves/andrei_kirilenko.jpg' },
       { tim: 'Timberwolves', ime: 'Malcolm Lee', pozicija: 'Guard', broj: '8', slika: '/images/Timberwolves/malcolm_lee.jpg' },
       { tim: 'Timberwolves', ime: 'Kevin Love', pozicija: 'Forward', broj: '42', slika: '/images/Timberwolves/kevin_love.jpg' },
       { tim: 'Timberwolves', ime: 'Nikola Pekovic', pozicija: 'Center', broj: '14', slika: '/images/Timberwolves/nikola_pekovic.jpg' },
       { tim: 'Timberwolves', ime: 'Luke Ridnour', pozicija: 'Guard', broj: '13', slika: '/images/Timberwolves/luke_ridnour.jpg' },
       { tim: 'Timberwolves', ime: 'Brandon Roy', pozicija: 'Guard', broj: '3', slika: '/images/Timberwolves/brandon_roy.jpg' },
       { tim: 'Timberwolves', ime: 'Ricky Rubio', pozicija: 'Guard', broj: '9', slika: '/images/Timberwolves/ricky_rubio.jpg' },
       { tim: 'Timberwolves', ime: 'Alexey Shved', pozicija: 'Guard', broj: '1', slika: '/images/Timberwolves/alexey_shved.jpg' },
       { tim: 'Timberwolves', ime: 'Greg Stiemsma', pozicija: 'Center', broj: '34', slika: '/images/Timberwolves/greg_stiemsma.jpg' },
       { tim: 'Timberwolves', ime: 'Derrick Williams', pozicija: 'Forward', broj: '7', slika: '/images/Timberwolves/derrick_williams.jpg' },
       { tim: 'Nuggets', ime: 'Corey Brewer', pozicija: 'Forward', broj: '13', slika: '/images/Nuggets/corey_brewer.jpg' },
       { tim: 'Nuggets', ime: 'Wilson Chandler', pozicija: 'Forward', broj: '21', slika: '/images/Nuggets/wilson_chandler.jpg' },
       { tim: 'Nuggets', ime: 'Kenneth Faried', pozicija: 'Forward', broj: '35', slika: '/images/Nuggets/kenneth_faried.jpg' },
       { tim: 'Nuggets', ime: 'Danilo Gallinari', pozicija: 'Forward', broj: '8', slika: '/images/Nuggets/danilo_gallinari.jpg' },
       { tim: 'Nuggets', ime: 'Andre Iguodala', pozicija: 'Forward', broj: '35', slika: '/images/Nuggets/andre_iguodala.jpg' },
       { tim: 'Nuggets', ime: 'Kosta Koufos', pozicija: 'Center', broj: '41', slika: '/images/Nuggets/kosta_koufos.jpg' },
       { tim: 'Nuggets', ime: 'JaVale McGee', pozicija: 'Center', broj: '34', slika: '/images/Nuggets/javale_mcgee.jpg' },
       { tim: 'Nuggets', ime: 'Andre Miller', pozicija: 'Guard', broj: '24', slika: '/images/Nuggets/andre_miller.jpg' },
       { tim: 'Nuggets', ime: 'Kenneth Faried', pozicija: 'Forward', broj: '35', slika: '/images/Nuggets/kenneth_faried.jpg' },
       { tim: 'Nuggets', ime: 'Timofey Mozgov', pozicija: 'Center', broj: '25', slika: '/images/Nuggets/timofey_mozgov.jpg' },
       { tim: 'Nuggets', ime: 'Anthony Randolph', pozicija: 'Forward', broj: '15', slika: '/images/Nuggets/anthony_randolph.jpg' },
       { tim: 'Jazz', ime: 'Raja Bell', pozicija: 'Guard', broj: '19', slika: '/images/Jazz/raja_bell.jpg' },
       { tim: 'Jazz', ime: 'Jeremy Evans', pozicija: 'Forward', broj: '40', slika: '/images/Jazz/jeremy_evans.jpg' },
       { tim: 'Jazz', ime: 'Derrick Favors', pozicija: 'Forward', broj: '15', slika: '/images/Jazz/derrick_favors.jpg' },
       { tim: 'Jazz', ime: 'Randy Foye', pozicija: 'Guard', broj: '8', slika: '/images/Jazz/randy_foye.jpg' },
       { tim: 'Jazz', ime: 'Gordon Hayward', pozicija: 'Forward', broj: '20', slika: '/images/Jazz/gordon_hayward.jpg' },
       { tim: 'Jazz', ime: 'Al Jefferson', pozicija: 'Center', broj: '25', slika: '/images/Jazz/al_jefferson.jpg' },
       { tim: 'Jazz', ime: 'Enes Kanter', pozicija: 'Center', broj: '0', slika: '/images/Jazz/enes_kanter.jpg' },
       { tim: 'Jazz', ime: 'Paul Millsap', pozicija: 'Forward', broj: '24', slika: '/images/Jazz/paul_millsap.jpg' },
       { tim: 'Jazz', ime: 'Jamaal Tinsley', pozicija: 'Guard', broj: '6', slika: '/images/Jazz/jamaal_tinsley.jpg' },
       { tim: 'Jazz', ime: 'Earl Watson', pozicija: 'Guard', broj: '11', slika: '/images/Jazz/earl_watson.jpg' },
       { tim: 'Jazz', ime: 'Mo Williams', pozicija: 'Guard', broj: '5', slika: '/images/Jazz/maurice_williams.jpg' },
       { tim: 'Jazz', ime: 'Marvin Williams', pozicija: 'Forward', broj: '2', slika: '/images/Jazz/marvin_williams.jpg' },
       { tim: 'Spurs', ime: 'DeJuan Blair', pozicija: 'Center', broj: '45', slika: '/images/Spurs/dejuan_blair.jpg' },
       { tim: 'Spurs', ime: 'Matt Bonner', pozicija: 'Forward', broj: '15', slika: '/images/Spurs/matt_bonner.jpg' },
       { tim: 'Spurs', ime: 'Nando De Colo', pozicija: 'Guard', broj: '25', slika: '/images/Spurs/nando_de_colo.jpg' },
       { tim: 'Spurs', ime: 'Boris Diaw', pozicija: 'Forward', broj: '33', slika: '/images/Spurs/boris_diaw.jpg' },
       { tim: 'Spurs', ime: 'Tim Duncan', pozicija: 'Forward', broj: '21', slika: '/images/Spurs/tim_duncan.jpg' },
       { tim: 'Spurs', ime: 'Manu Ginobili', pozicija: 'Guard', broj: '20', slika: '/images/Spurs/emanuel_ginobili.jpg' },
       { tim: 'Spurs', ime: 'Danny Green', pozicija: 'Guard', broj: '4', slika: '/images/Spurs/daniel_green.jpg' },
       { tim: 'Spurs', ime: 'Stephen Jackson', pozicija: 'Forward', broj: '3', slika: '/images/Spurs/stephen_jackson.jpg' },
       { tim: 'Spurs', ime: 'Kawhi Leonard', pozicija: 'Forward', broj: '2', slika: '/images/Spurs/kawhi_leonard.jpg' },
       { tim: 'Spurs', ime: 'Patty Mills', pozicija: 'Guard', broj: '8', slika: '/images/Spurs/patrick_mills.jpg' },
       { tim: 'Spurs', ime: 'Gary Neal', pozicija: 'Guard', broj: '14', slika: '/images/Spurs/gary_neal.jpg' },
       { tim: 'Spurs', ime: 'Tony Parker', pozicija: 'Guard', broj: '9', slika: '/images/Spurs/tony_parker.jpg' },
       { tim: 'Spurs', ime: 'Tiago Splitter', pozicija: 'Center', broj: '22', slika: '/images/Spurs/tiago_splitter.jpg' },
       { tim: 'Hornets', ime: 'Al-Farouq Aminu', pozicija: 'Forward', broj: '0', slika: '/images/Hornets/al-farouq_aminu.jpg' },
       { tim: 'Hornets', ime: 'Ryan Anderson', pozicija: 'Forward', broj: '33', slika: '/images/Hornets/ryan_j_anderson.jpg' },
       { tim: 'Hornets', ime: 'Antony Davis', pozicija: 'Forward', broj: '23', slika: '/images/Hornets/anthony_davis.jpg' },
       { tim: 'Hornets', ime: 'Eric Gordon', pozicija: 'Guard', broj: '10', slika: '/images/Hornets/eric_gordon.jpg' },
       { tim: 'Hornets', ime: 'Robin Lopez', pozicija: 'Center', broj: '15', slika: '/images/Hornets/robin_lopez.jpg' },
       { tim: 'Hornets', ime: 'Roger Mason', pozicija: 'Guard', broj: '8', slika: '/images/Hornets/roger_mason-jr.jpg' },
       { tim: 'Hornets', ime: 'Darius Miller', pozicija: 'Forward', broj: '2', slika: '/images/Hornets/darius_miller.jpg' },
       { tim: 'Hornets', ime: 'Austin Rivers', pozicija: 'Guard', broj: '25', slika: '/images/Hornets/austin_rivers.jpg' },
       { tim: 'Hornets', ime: 'Brian Roberts', pozicija: 'Guard', broj: '22', slika: '/images/Hornets/brian_roberts.jpg' },
       { tim: 'Hornets', ime: 'Jason Smith', pozicija: 'Forward', broj: '14', slika: '/images/Hornets/jason_smith.jpg' },
       { tim: 'Hornets', ime: 'Lance Thomas', pozicija: 'Forward', broj: '42', slika: '/images/Hornets/lance_thomas.jpg' },
       { tim: 'Hornets', ime: 'Greivis Vasquez', pozicija: 'Guard', broj: '21', slika: '/images/Hornets/greivis_vasquez.jpg' },
       { tim: 'Rockets', ime: 'Cole Aldrich', pozicija: 'Center', broj: '31', slika: '/images/Rockets/cole_aldrich.jpg' },
       { tim: 'Rockets', ime: 'Omer Asik', pozicija: 'Center', broj: '3', slika: '/images/Rockets/omer_asik.jpg' },
       { tim: 'Rockets', ime: 'Daequan Cook', pozicija: 'Guard', broj: '14', slika: '/images/Rockets/daequan_cook.png' },
       { tim: 'Rockets', ime: 'Carsol Delfino', pozicija: 'Forward', broj: '10', slika: '/images/Rockets/carlos_delfino.jpg' },
       { tim: 'Rockets', ime: 'Toney Douglas', pozicija: 'Guard', broj: '15', slika: '/images/Rockets/toney_douglas.jpg' },
       { tim: 'Rockets', ime: 'James Harden', pozicija: 'Guard', broj: '13', slika: '/images/Rockets/james_harden.jpg' },
       { tim: 'Rockets', ime: 'Terrence Jones', pozicija: 'Forward', broj: '6', slika: '/images/Rockets/terrence_jones.png' },
       { tim: 'Rockets', ime: 'Jeremy Lin', pozicija: 'Guard', broj: '7', slika: '/images/Rockets/jeremy_lin.jpg' },
       { tim: 'Rockets', ime: 'Marcus Morris', pozicija: 'Forward', broj: '2', slika: '/images/Rockets/marcus_morris.jpg' },
       { tim: 'Rockets', ime: 'Chandler Parsons', pozicija: 'Forward', broj: '25', slika: '/images/Rockets/chandler_parsons.jpg' },
       { tim: 'Rockets', ime: 'Patrick Patterson', pozicija: 'Forward', broj: '54', slika: '/images/Rockets/patrick_patterson.jpg' },
       { tim: 'Rockets', ime: 'Greg Smith', pozicija: 'Center', broj: '4', slika: '/images/Rockets/greg_smith.jpg' },
       { tim: 'Rockets', ime: 'Royce White', pozicija: 'Forward', broj: '30', slika: '/images/Rockets/royce_white.jpg' },
       { tim: 'Grizzlies', ime: 'Tony Allen', pozicija: 'Guard', broj: '9', slika: '/images/Grizzlies/tony_allen.jpg' },
       { tim: 'Grizzlies', ime: 'Darrell Arthur', pozicija: 'Forward', broj: '00', slika: '/images/Grizzlies/darrell_arthur.jpg' },
       { tim: 'Grizzlies', ime: 'Jerryd Bayless', pozicija: 'Guard', broj: '7', slika: '/images/Grizzlies/jerryd_bayless.jpg' },
       { tim: 'Grizzlies', ime: 'Mike Conley', pozicija: 'Guard', broj: '11', slika: '/images/Grizzlies/mike_conley.jpg' },
       { tim: 'Grizzlies', ime: 'Wayne Ellington', pozicija: 'Guard', broj: '3', slika: '/images/Grizzlies/wayne_ellington.jpg' },
       { tim: 'Grizzlies', ime: 'Marc Gasol', pozicija: 'Center', broj: '33', slika: '/images/Grizzlies/marc_gasol.jpg' },
       { tim: 'Grizzlies', ime: 'Rudy Gay', pozicija: 'Forward', broj: '22', slika: '/images/Grizzlies/rudy_gay.jpg' },
       { tim: 'Grizzlies', ime: 'Hamed Haddadi', pozicija: 'Center', broj: '15', slika: '/images/Grizzlies/hamed_haddadi.jpg' },
       { tim: 'Grizzlies', ime: 'Quincy Pondexter', pozicija: 'Forward', broj: '20', slika: '/images/Grizzlies/quincy_pondexter.jpg' },
       { tim: 'Grizzlies', ime: 'Zach Randolph', pozicija: 'Forward', broj: '50', slika: '/images/Grizzlies/zach_randolph.jpg' },
       { tim: 'Grizzlies', ime: 'Marreese Speights', pozicija: 'Forward', broj: '5', slika: '/images/Grizzlies/marreese_speights.jpg' },
       { tim: 'Mavericks', ime: 'Rodrique Beabois', pozicija: 'guard', broj: '2', slika: '/images/Mavericks/rodrigue_beaubois.jpg' },
       { tim: 'Mavericks', ime: 'Elton Brand', pozicija: 'Forward', broj: '42', slika: '/images/Mavericks/elton_brand.jpg' },
       { tim: 'Mavericks', ime: 'Vince Carter', pozicija: 'Forward', broj: '25', slika: '/images/Mavericks/vince_carter.jpg' },
       { tim: 'Mavericks', ime: 'Darren Collison', pozicija: 'Guard', broj: '3', slika: '/images/Mavericks/darren_collison.jpg' },
       { tim: 'Mavericks', ime: 'Jae Crowder', pozicija: 'Forward', broj: '9', slika: '/images/Mavericks/jae_crowder.jpg' },
       { tim: 'Mavericks', ime: 'Jared Cunningham', pozicija: 'Guard', broj: '1', slika: '/images/Mavericks/jared_cunningham.jpg' },
       { tim: 'Mavericks', ime: 'Bernard James', pozicija: 'Center', broj: '5', slika: '/images/Mavericks/bernard_james.jpg' },
       { tim: 'Mavericks', ime: 'Dahntay Jones', pozicija: 'Guard', broj: '30', slika: '/images/Mavericks/dahntay_jones.jpg' },
       { tim: 'Mavericks', ime: 'Dominique Jones', pozicija: 'Guard', broj: '20', slika: '/images/Mavericks/dominique_jones.jpg' },
       { tim: 'Mavericks', ime: 'Chris Kaman', pozicija: 'Center', broj: '35', slika: '/images/Mavericks/chris_kaman.jpg' },
       { tim: 'Mavericks', ime: 'Shawn Marion', pozicija: 'Forward', broj: '0', slika: '/images/Mavericks/shawn_marion.jpg' },
       { tim: 'Mavericks', ime: 'O.J. Mayo', pozicija: 'guard', broj: '32', slika: '/images/Mavericks/oj_mayo.jpg' },
       { tim: 'Mavericks', ime: 'Troy Murphy', pozicija: 'Forward', broj: '6', slika: '/images/Mavericks/troy_murphy.jpg' },
       { tim: 'Mavericks', ime: 'Dirk Nowitzki', pozicija: 'Forward', broj: '41', slika: '/images/Mavericks/dirk_nowitzki.jpg' },
       { tim: 'Mavericks', ime: 'Brendan Wright', pozicija: 'Center', broj: '34', slika: '/images/Mavericks/brandan_wright.jpg' },
    ];

    //Функција за поставување на слика во img tag
    //Треба да е зададено ID на img tag и објект од кој се зема патеката за сликата
    function setImage(idImage, item) {
        var pic = document.getElementById(idImage);
        pic.src = item.slika;
    };

    //Функцијата враќа рандом објект од листата sliki
    //Се користи за добивање на 5 слики за пакет
    function getRandom() {
        var rand = Math.floor(Math.random() * 197);
        var item = sliki[rand];
        return item;
    }

    var publicMembers = {
        setImage: setImage,
        getRandom: getRandom,
        getSearchedPlayer: getSearchedPlayer
    };

    var slikiArr = new WinJS.Binding.List(sliki);
    //ФУНКЦИЈА ЗА ПРЕБАРУВАЊЕ НА ИГРАЧИ/ТИМОВИ ОД ЛИСТАТА slikiArr
    //ВРАЌА ФИЛТРИРАНА ЛИСТА ОД ИГРАЧИ
    //СЕ КОРИСТИ ЗА Search Charm
    function getSearchedPlayer(player) {
        return slikiArr.createFiltered(function (item) {
            return (item.ime.search(player) !== -1 || item.tim.search(player) !== -1);
        });
    }

    WinJS.Namespace.define("fullData", publicMembers);
})();